### ISSUE TITLE
恳请指教数据源的生成方式

### ISSUE THREAD

**Issue by engvuchen** [liuyanchen1994/iView-helper#8]
https://github.com/liuyanchen1994/iView-helper/blob/master/src/config/ui-tags.json
看了下源码，自动补全的数据源是这个文件；

我的方案是通过在文件中写备注才能获取到对应数据；
https://github.com/engvuchen/helper-demo

感觉大佬你的方案更好，求指教用工具解析组件库的方法

**Comment by liuyanchen1994** [comment]
就是通过正则匹配json文件的，vsocde 官方的自动补全有例子，可能你用的错了API

**Comment by engvuchen** [comment]
> 就是通过正则匹配json文件的，vsocde 官方的自动补全有例子，可能你用的错了API

那大佬你的 JSON 文件是如何生成呢？我是通过获取文件中的备注来生成这个JSON数据源

**Comment by liuyanchen1994** [comment]
项目的那些JSON 文件是 自己一点点手敲的
